### ISSUE TITLE
ValueError: A 2-dimensional array must be passed.

### ISSUE THREAD

**Issue by tomas-pluskal** [keiserlab/e3fp#30]
````
2018-09-01 10:14:15,307|ERROR|Error generating fingerprints for Cisplatin.
Traceback (most recent call last):
 File "e3fp/fingerprint/generate.py", line 157, in fprints_dict_from_mol
   fingerprinter.run(conf, mol)
 File "/home/pluskal/.local/lib/python3.6/site-packages/e3fp/fingerprint/fprinter.py", line 162, in run
   self.initialize_conformer(conf)
 File "/home/pluskal/.local/lib/python3.6/site-packages/e3fp/fingerprint/fprinter.py", line 235, in initialize_conformer
   bound_atoms_dict=self.bound_atoms_dict)
 File "/home/pluskal/.local/lib/python3.6/site-packages/e3fp/fingerprint/fprinter.py", line 480, in __init__
   self.distance_matrix = array_ops.make_distance_matrix(atom_coords)
 File "/home/pluskal/.local/lib/python3.6/site-packages/e3fp/fingerprint/array_ops.py", line 56, in make_distance_matrix
   return squareform(pdist(coords))
 File "/lab/solexa_weng/testtube/miniconda3/envs/e3fp_env/lib/python3.6/site-packages/scipy/spatial/distance.py", line 1872, in pdist
   raise ValueError('A 2-dimensional array must be passed.')
ValueError: A 2-dimensional array must be passed.
````

**Comment by tomas-pluskal** [comment]
[Cisplatin.sdf.bz2.zip](https://github.com/keiserlab/e3fp/files/2342419/Cisplatin.sdf.bz2.zip)

**Comment by sdaxen** [comment]
Can you provide a code snippet that fails with the above error?
