### ISSUE TITLE
"Error retrieving mol from sdf"

### ISSUE THREAD

**Issue by slchan3** [keiserlab/e3fp#57]
I tried the following, similar to the "Fingerprinting CLI" section of the manual.
$ python $E3FP/e3fp/fingerprint/generate.py -o outdir --out_ext .fp.gz -l log.txt CHEMBL101978.sdf

It did not run. The logfile complains that there is an error retrieving the molecule from the sdf.
$ cat log.txt
2021-04-08 13:04:43,398|INFO|Initializing E3FP generation.
2021-04-08 13:04:43,398|INFO|Getting SDF files
2021-04-08 13:04:43,398|INFO|SDF File Number: 2058
2021-04-08 13:04:43,398|INFO|Out Directory Basename: outdir
2021-04-08 13:04:43,398|INFO|Out Extension: .fp.gz
2021-04-08 13:04:43,398|INFO|Database File: fingerprints.fpz
2021-04-08 13:04:43,398|INFO|Max First Conformers: 3
2021-04-08 13:04:43,398|INFO|Bits: 4294967296
2021-04-08 13:04:43,398|INFO|Level/Max Iterations: 5
2021-04-08 13:04:43,398|INFO|Shell Radius Multiplier: 1.718
2021-04-08 13:04:43,398|INFO|Stereo Mode: True
2021-04-08 13:04:43,398|INFO|Connected-only mode: on
2021-04-08 13:04:43,398|INFO|Invariant type: Daylight
2021-04-08 13:04:43,398|INFO|Parallel Mode: processes
2021-04-08 13:04:43,398|INFO|Starting
2021-04-08 13:04:43,406|ERROR|Error retrieving mol from CHEMBL101978.sdf.

However, rdkit has no problem parsing this sdf.
>>> from rdkit import Chem
>>> for m in Chem.SDMolSupplier("CHEMBL101978.sdf"):
...   print (Chem.MolToSmiles(m))
... 
N#Cc1ccc(Cn2cncc2CCN[C@@H]2CCN(c3ccccc3)C2=O)cc1
N#Cc1ccc(Cn2cncc2CCN[C@@H]2CCN(c3ccccc3)C2=O)cc1
N#Cc1ccc(Cn2cncc2CCN[C@@H]2CCN(c3ccccc3)C2=O)cc1
N#Cc1ccc(Cn2cncc2CCN[C@@H]2CCN(c3ccccc3)C2=O)cc1

**Comment by sethaxen** [comment]
Can you provide the output of `e3fp.conformer.util.mol_from_sdf("CHEMBL101978.sdf")`? If it raises an error, can you include the full stacktrace?

If possible can you also provide the text of the sdf file?

**Comment by slchan3** [comment]
>>> e3fp.conformer.util.mol_from_sdf("CHEMBL101978.sdf")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "..../miniconda3/envs/e3fp/lib/python3.9/site-packages/e3fp-1.2.3-py3.9.egg/e3fp/conformer/util.py", line 330, in mol_from_sdf
    supplier = rdkit.Chem.ForwardSDMolSupplier(f)
ValueError: Need a binary mode file object like BytesIO or a file opened with mode 'b'

**Comment by sethaxen** [comment]
I've seen something like this before, and I think it's because RDKit changed how they do IO, and the approach we're using to recognize the extension and open the file in different modes is kind of a hack. A quick workaround should be to gzip or bzip the file: `gzip CHEMBL101978.sdf`. Then load in `CHEMBL101978.sdf.gz`, which it should have no problem reading in. 🤞

**Comment by slchan3** [comment]
Thanks Seth. I'll zip my file before feeding it into e3fp then.
Ling
