### ISSUE TITLE
Problem with pipeline.fprints_from_mol() with rdkits Chem.MolFromXYZBlock()

### ISSUE THREAD

**Issue by Ltwicke** [keiserlab/e3fp#79]
Hello, first of all, cool idea of a 3D extension to the ECFP, i would like to use them in my project.

I have created rdkit mol objects with `Chem.MolFromXYZBlock` already and used them with the mordred 3D featurizer for conformers of my chemical species.
When i tried to use the function `pipeline.fprints_from_mol()` on the mol object that was created with `Chem.MolFromXYZBlock`, i get the following error:

_2024-11-13 01:31:20,361|INFO|Generating fingerprints for Hi.
2024-11-13 01:31:20,363|ERROR|Error generating fingerprints for Hi.
Traceback (most recent call last):
  File "/scratch/ge56zaw_mount_other/ge56zaw_local/0envs/TF_m/lib/python3.11/site-packages/e3fp/fingerprint/generate.py", line 188, in fprints_dict_from_mol
    fingerprinter.run(conf, mol)
  File "/scratch/ge56zaw_mount_other/ge56zaw_local/0envs/TF_m/lib/python3.11/site-packages/e3fp/fingerprint/fprinter.py", line 177, in run
    self.initialize_mol(mol)
  File "/scratch/ge56zaw_mount_other/ge56zaw_local/0envs/TF_m/lib/python3.11/site-packages/e3fp/fingerprint/fprinter.py", line 244, in initialize_mol
    self.initialize_identifiers()
  File "/scratch/ge56zaw_mount_other/ge56zaw_local/0envs/TF_m/lib/python3.11/site-packages/e3fp/fingerprint/fprinter.py", line 267, in initialize_identifiers
    self.init_identifiers = identifiers_from_invariants(
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/scratch/ge56zaw_mount_other/ge56zaw_local/0envs/TF_m/lib/python3.11/site-packages/e3fp/fingerprint/fprinter.py", line 767, in identifiers_from_invariants
    identifiers = [
                  ^
  File "/scratch/ge56zaw_mount_other/ge56zaw_local/0envs/TF_m/lib/python3.11/site-packages/e3fp/fingerprint/fprinter.py", line 768, in <listcomp>
    hash_int64_array(
  File "/scratch/ge56zaw_mount_other/ge56zaw_local/0envs/TF_m/lib/python3.11/site-packages/e3fp/fingerprint/fprinter.py", line 727, in hash_int64_array
    hashed_int = mmh3.hash(array, seed)
                 ^^^^^^^^^^^^^^^^^^^^^^
TypeError: argument 1 must be read-only bytes-like object, not 'numpy.ndarray'_

-------------------------------------------------------------------------------------

Where my own traceback in the notebook says:

_ValueError                                Traceback (most recent call last)
Cell In[48], line 1
----> 1 e3fp_example = fprints_from_mol(mol, fprint_params=fp_config)

File /scratch/ge56zaw_mount_other/ge56zaw_local/0envs/TF_m/lib/python3.11/site-packages/e3fp/pipeline.py:59, in fprints_from_mol(mol, fprint_params, save)
     57 fprints_dict = fprints_dict_from_mol(mol, save=save, **fprint_params)
     58 level = fprint_params.get("level", -1)
---> 59 fprints_list = fprints_from_fprints_dict(fprints_dict, level=level)
     60 return fprints_list

File /scratch/ge56zaw_mount_other/ge56zaw_local/0envs/TF_m/lib/python3.11/site-packages/e3fp/pipeline.py:50, in fprints_from_fprints_dict(fprints_dict, level)
     47 def fprints_from_fprints_dict(fprints_dict, level=-1):
     48     """Get fingerprint at `level` from dict of level to fingerprint."""
     49     fprints_list = fprints_dict.get(
---> 50         level, fprints_dict[max(fprints_dict.keys())]
     51     )
     52     return fprints_list

ValueError: max() arg is an empty sequence_

--------------------------------------------------------------------------------------

Im following exactly the configurations from the documentation under "**Pipeline methods**". I suppose it has something to do with the initial featurization and the fact, that atoms are written to the mol object differently in  `Chem.MolFromXYZBlock`?

I would love to hear from you soonish, so i can implement this featurization also into the competition.

Thanks

**Comment by sethaxen** [comment]
Thanks for the issue. Could you provide a file containing one of these Mols that I can use to try to diagnose the problem? Please verify that after re-loading the file the error you're seeing persists.

**Comment by Ltwicke** [comment]
Hey, thanks for the quick reply!

Here is what you should need:

example xyz string:

'58\n\nO -6.428488 3.127504 -2.134294\nC -5.408320 2.490457 -1.869355\nO -4.329005 3.085371 -1.330071\nH -3.611949 2.443970 -1.178573\nC -5.256441 0.994994 -2.157353\nO -4.135787 0.458230 -1.422550\nC -4.345621 0.012469 -0.124432\nC -5.472222 0.381434 0.622750\nC -5.590240 -0.088032 1.936273\nC -4.605835 -0.906931 2.485861\nC -3.476210 -1.277600 1.732917\nC -3.336236 -0.815435 0.413883\nC -2.136098 -1.162532 -0.444380\nC -1.315740 -2.327375 0.112455\nH -0.352352 -2.382190 -0.404096\nH -1.833400 -3.271845 -0.074259\nC -1.096028 -2.182836 1.632440\nC -2.455447 -2.201959 2.356479\nH -2.838541 -3.228374 2.336133\nH -2.323620 -1.954522 3.414669\nO -0.343435 -3.332790 2.113204\nH 0.393045 -3.528175 1.517188\nC -0.313316 -0.897120 1.996828\nH 0.063214 -0.940291 3.026646\nH -0.945096 -0.002251 1.894513\nO 0.820093 -0.755364 1.092851\nC 1.725670 0.190248 1.430276\nO 1.625137 0.854216 2.488401\nN 2.749118 0.355118 0.516134\nC 2.816426 -0.432883 -0.692922\nC 3.042805 0.222249 -1.917391\nC 3.111344 -0.510246 -3.104419\nC 2.944566 -1.896009 -3.041352\nC 2.724574 -2.572048 -1.838883\nC 2.668449 -1.830358 -0.655517\nH 2.518737 -2.339126 0.288835\nH 2.613893 -3.649293 -1.824104\nF 3.003592 -2.609166 -4.188334\nH 3.284067 -0.018630 -4.053852\nH 3.167075 1.299546 -1.937058\nC 3.708313 1.420608 0.683039\nC 3.330549 2.691297 1.149271\nC 4.293139 3.695236 1.295972\nC 5.632400 3.459345 0.973229\nC 6.030662 2.200914 0.507312\nC 5.066688 1.203091 0.377766\nF 5.457924 -0.020349 -0.050151\nH 7.064079 1.989173 0.262245\nH 6.366338 4.248233 1.086993\nH 3.991167 4.670322 1.659537\nH 2.298600 2.888690 1.406154\nH -1.492622 -0.279775 -0.537298\nH -2.469454 -1.393450 -1.458173\nH -4.705784 -1.263734 3.504934\nH -6.453557 0.193889 2.528250\nH -6.241443 1.023668 0.211732\nH -6.173568 0.439687 -1.922938\nH -5.026458 0.845395 -3.219973'

Then i proceed with 

```
example_mol = Chem.MolFromXYZBlock(xyz_block)
rdDetermineBonds.DetermineBonds(example_mol, charge=0)
```

where i use `from rdkit.Chem import rdDetermineBonds` to determine the bonds of the molecule. 

I then have to proceed to give it a name for whatever reason:

`example_mol.SetProp("_Name", "Hi")`

Configure the E3fp:

```
fp_config = {"bits": 1024, "radius_multiplier": 1.5, "rdkit_invariants": True}
e3fp_example = fprints_from_mol(example_mol, fprint_params=fp_config)
```

The resulting error persist even after reloading.


Thanks

**Comment by sethaxen** [comment]
I've briefly looked into this, and the main issue here is some changes in mmh3 v5.0.0 that e3fp is not yet compatible with. Simply downgrading to mmh3 v4.1.0 should resolve this error. It's always a good idea to run the entire test suite in your environment before using e3fp. After doing that, it seems that e3fp may also have some compatibility issues with numpy v2, so I recommend also downgrading to scipy==1.12.0 numpy==1.26.4. I'll also work on compatibility with these latest releases, but it may take a few weeks.

Here's what I get after downgrading:
```python
import e3fp.pipeline
import rdkit.Chem.rdDetermineBonds
import rdkit.Chem
xyz_block = '''58

O -6.428488 3.127504 -2.134294
C -5.408320 2.490457 -1.869355
O -4.329005 3.085371 -1.330071
H -3.611949 2.443970 -1.178573
C -5.256441 0.994994 -2.157353
O -4.135787 0.458230 -1.422550
C -4.345621 0.012469 -0.124432
C -5.472222 0.381434 0.622750
C -5.590240 -0.088032 1.936273
C -4.605835 -0.906931 2.485861
C -3.476210 -1.277600 1.732917
C -3.336236 -0.815435 0.413883
C -2.136098 -1.162532 -0.444380
C -1.315740 -2.327375 0.112455
H -0.352352 -2.382190 -0.404096
H -1.833400 -3.271845 -0.074259
C -1.096028 -2.182836 1.632440
C -2.455447 -2.201959 2.356479
H -2.838541 -3.228374 2.336133
H -2.323620 -1.954522 3.414669
O -0.343435 -3.332790 2.113204
H 0.393045 -3.528175 1.517188
C -0.313316 -0.897120 1.996828
H 0.063214 -0.940291 3.026646
H -0.945096 -0.002251 1.894513
O 0.820093 -0.755364 1.092851
C 1.725670 0.190248 1.430276
O 1.625137 0.854216 2.488401
N 2.749118 0.355118 0.516134
C 2.816426 -0.432883 -0.692922
C 3.042805 0.222249 -1.917391
C 3.111344 -0.510246 -3.104419
C 2.944566 -1.896009 -3.041352
C 2.724574 -2.572048 -1.838883
C 2.668449 -1.830358 -0.655517
H 2.518737 -2.339126 0.288835
H 2.613893 -3.649293 -1.824104
F 3.003592 -2.609166 -4.188334
H 3.284067 -0.018630 -4.053852
H 3.167075 1.299546 -1.937058
C 3.708313 1.420608 0.683039
C 3.330549 2.691297 1.149271
C 4.293139 3.695236 1.295972
C 5.632400 3.459345 0.973229
C 6.030662 2.200914 0.507312
C 5.066688 1.203091 0.377766
F 5.457924 -0.020349 -0.050151
H 7.064079 1.989173 0.262245
H 6.366338 4.248233 1.086993
H 3.991167 4.670322 1.659537
H 2.298600 2.888690 1.406154
H -1.492622 -0.279775 -0.537298
H -2.469454 -1.393450 -1.458173
H -4.705784 -1.263734 3.504934
H -6.453557 0.193889 2.528250
H -6.241443 1.023668 0.211732
H -6.173568 0.439687 -1.922938
H -5.026458 0.845395 -3.219973'''

example_mol = rdkit.Chem.MolFromXYZBlock(xyz_block)
rdkit.Chem.rdDetermineBonds.DetermineBonds(example_mol)
example_mol.SetProp("_Name", "Hi")

fp_config = {"bits": 1024, "radius_multiplier": 1.5, "rdkit_invariants": True}
e3fp_example = e3fp.pipeline.fprints_from_mol(example_mol, fprint_params=fp_config)
```
```python
>>> e3fp_example
[Fingerprint(indices=array([2, 32, 39, 58, 73, 111, 141, 169, 171, 176, 182, 213, 214, 218, 221, 243, 274, 307, 327, 360, 369, 385, 389, 392, 401, 421, 425, 428, 429, 438, 473, 476, 512, 526, 529, 532, 562, 566, 569, 572, 575, 584, 652, 666, 667, 682, 711, 714, 772, 778, 780, 787, 820, 831, 861, 864, 882, 886, 914, 917, 920, 928, 942, 945, 958, 964, 988, 994, 1017]), level=5, bits=1024, name=Hi_0)]
```

> I then have to proceed to give it a name for whatever reason:
> 
> `example_mol.SetProp("_Name", "Hi")`

The name is necessary for I/O in case that is requested, but it's true that we shouldn't require this if no I/O is performed. I'll push a fix.

**Comment by sethaxen** [comment]
@Ltwicke e3fp v1.2.6 (just released on pypi) should resolve all of the problems raised here. If you're using the conda-forge version, you may need to wait a day or so until the update is on conda-forge. If you face any other problems, please let me know.
